export const search = document.querySelector(".searchbtn button");
export const inputSearch = document.querySelector("#search");
export const cityElement = document.querySelector(".city");
export const tempElement = document.querySelector(".temp");
export const hourlyContainer = document.querySelector(".hourlytemp");
export const errorElement = document.querySelector(".error-message");
export const loader = document.querySelector(".loading");
export const background = document.querySelector(".background");
export const suggestions = document.querySelector(".suggestions");
export const weather = document.querySelector("#weather");
export const favbtn = document.querySelector('.fav-btn')
export const favourites = document.querySelector('.favourites')
export const uvindex = document.querySelector('.extra-info-card-uvindex')
export const FAV_KEY = 'favBtn'
export const weatherIcons = {
  "clear-day": '<span class="material-symbols-outlined">clear_day</span>',
  "clear-night": '<span class="material-symbols-outlined">nightlight</span>',
  "rain": '<span class="material-symbols-outlined">rainy</span>',
  "snow": '<span class="material-symbols-outlined">weather_snowy</span>',
  "fog": '<span class="material-symbols-outlined">foggy</span>',
  "wind": '<span class="material-symbols-outlined">air</span>',
  "cloudy": '<span class="material-symbols-outlined">cloud</span>',
  "partly-cloudy-day": '<span class="material-symbols-outlined">partly_cloudy_day</span>',
  "partly-cloudy-night": '<span class="material-symbols-outlined">partly_cloudy_night</span>',
};;
